### ISSUE TITLE
Flying after death

### ISSUE THREAD

**Issue by Mrgremlin7** [Strafbefehl/DeluxeHubReloaded#32]
I own a server and i use multiverse core. Theres a bug where if i die, it lets me fly. I use the deluxehub world disable feture.

**Comment by BasisZock** [comment]
Hey, I found a simple fix for this if you don't want flight (it completely disables it and works for me):
You need to remove the FlyCommand.class file under \fun\lewisdev\deluxehub\command\commands.

I did this by opening the file in WinRAR, navigating through the folders, and deleting it. However, this completely disables /fly, so make a backup first. It didn’t break anything for me, but I still recommend it just in case.

**Comment by BasisZock** [comment]
Hello, I have fixed it myself and created a pull request. If you already want the fixed version, with no other changes than the fix, you can download it here: https://github.com/BasisZock/DeluxeHubReloaded/releases/tag/final

**Comment by AnTi3z** [comment]
Still have that bug. I don't see the necessary fix in the @BasisZock  repository
Same #33

**Comment by BasisZock** [comment]
It is now fixed in the newest official release here

**Comment by AnTi3z** [comment]
> It is now fixed in the newest official release here

Not, bug is still present. Every time if someone die flying is activating for him. There is no such bug in upstream DeluxeHub, but there is another bug with second hand.
