### ISSUE TITLE
Can fly in survival

### ISSUE THREAD

**Issue by Sebacul26** [Strafbefehl/DeluxeHubReloaded#33]
I have a server and only when i have this plugin it lets me fly on survival, and i dont know how to disable it

**Comment by BasisZock** [comment]
Hey, I found a simple fix for this if you don't want flight (it completely disables it and works for me):
You need to remove the FlyCommand.class file under \fun\lewisdev\deluxehub\command\commands.

I did this by opening the file in WinRAR, navigating through the folders, and deleting it. However, this completely disables /fly, so make a backup first. It didn’t break anything for me, but I still recommend it just in case.

**Comment by BasisZock** [comment]
Hello, I have fixed it myself and created a pull request. If you already want the fixed version, with no other changes than the fix, you can download it here: https://github.com/BasisZock/DeluxeHubReloaded/releases/tag/final

**Comment by AnTi3z** [comment]
Still have that bug. I don't see the necessary fix in the @BasisZock  repository
Same #32
